[package]
name = "audio-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.3"
termion = "3.0.0"

[dev-dependencies]
faux = "0.1.10"
mockall = "0.12.1"
