name: 🧪 Tests

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Install libasound
        run: sudo apt install libasound2-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: cargo test --all-features

      - name: Format code
        run: cargo fmt --all -- --check
      
      - name: Lint code
        run: cargo clippy --all-features -- -D warnings
